files:
  - source: /locale/en/**/*.md
    translation: /localized/%two_letters_code%/**/%original_file_name%
  - source: /locale/en/**/*.json
    translation: /localized/%two_letters_code%/**/%original_file_name%
